---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2018/12/24 下午7:57
---

--[[
    公共包引用的范围为http块；项目用到的非配置类都可以在此处配置；
    日志级别：
   ngx.STDERR
   ngx.EMERG
   ngx.ALERT
   ngx.CRIT
   ngx.ERR
   ngx.WARN
   ngx.NOTICE
   ngx.INFO
   ngx.DEBUG
]]
-- 加载cjson
cjson = require("cjson");
-- 加载string
string = require("string");

--[[
   项目内公共包配置
]]
-- 加载resty.core
require("resty.core");