---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2019/3/7 下午12:01
---

print("hello world.");

local function get_name()
    local first_name = "a";
    local second_name = "b";
    return first_name..second_name;
end

print(package.path);

print(get_name())