---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaoyueya.
--- DateTime: 2019/3/7 下午3:56
---

local print_log = { verison = "0.10" }

print_log.path = package.path;

return print_log